apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: x7b6vockp-go
  janus-idp.io/tekton: x7b6vockp-go
  backstage.io/kubernetes-id: x7b6vockp-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: x7b6vockp-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
